# Generated by Django 5.2 on 2025-05-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_treatment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='facility',
            field=models.CharField(blank=True, null=True),
        ),
    ]
